### ISSUE TITLE
A case for an interpolation option

### ISSUE THREAD

**Issue by d-v-b** [freeman-lab/showit#1]
Interpolation can prevent aliasing, which might be a desirable option for many images with high spatial frequency (raster plots, for example). On my 2013 13 inch Macbook air the following example displays a uniform black image despite the underlying data being highly nonuniform -- the white stripe in the data is aliased out due to undersampling, and this would be prevented via interpolation.

edit: I now see that `showit` calls `matplotlib.imshow()` with `interpolation = nearest`, which should handle aliasing just fine. Closing this :smile: 

```
import numpy as np
import showit as sit
%matplotlib inline

im = np.random.randn(1500, 1500)
im[:,1000] = 100
sit.image(im)
```

**Comment by freeman-lab** [comment]
thanks for flagging @d-v-b , the use of `nearest` was on master but not pypi, just bumped the version and published
